version: "2"
services:
  server:
    image: mastermindzh/generic_node
    volumes:
      - ./apps/server:/app
    ports:
      - 8001:8080

  scoreboard:
    image: mastermindzh/generic_node
    volumes:
      - ./apps/scoreboard:/app
    ports:
      - 8002:8080

  quiz-master:
    image: mastermindzh/generic_node
    volumes:
      - ./apps/quiz-master:/app
    ports:
      - 8003:8080

  team-app:
    image: mastermindzh/generic_node
    volumes:
      - ./apps/team-app:/app
    ports:
      - 8004:8080
  mongo:
    image: mongo
    volumes:
      - ./dbdata:/data/db
    ports:
      - 8009:27017
