swagger: "2.0"
info:
  description: "Quizzer application"
  version: "0.0.1"
  title: "Quizzer"
  contact:
    email: ""
  license:
    name: "MIT"
    url: "https://opensource.org/licenses/MIT"
host: ""
basePath: "/"
tags:
- name: "user"
  description: "Users"
schemes:
- "http"
paths:
  /user/{username}:
    get:
      tags:
      - "user"
      summary: "Get user by user name"
      description: "Get user by user name"
      operationId: "getUserByName"
      produces:
      - "application/json"
      parameters:
      - name: "username"
        in: "path"
        description: "The name that needs to be fetched."
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/User"
        400:
          description: "Invalid username supplied"
        404:
          description: "User not found"
definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      username:
        type: "string"
      password:
        type: "string"
